DATA_PATH = '../data/'
POS_TWEETS = DATA_PATH + 'train_pos.txt'
NEG_TWEETS = DATA_PATH + 'train_neg.txt'
POS_TWEETS_FULL = DATA_PATH + 'train_pos_full.txt'
NEG_TWEETS_FULL = DATA_PATH + 'train_neg_full.txt'
TEST_DATA = DATA_PATH + 'test_data.txt'
PREPROCESSED_DATA = DATA_PATH + 'preprocessed_tweets.txt'
PREPROCESSED_DATA_FULL = DATA_PATH + 'preprocessed_tweets_full.txt'
PREPROCESSED_DATA_TEST = DATA_PATH + 'preprocessed_tweets_test.txt'

GLOVE_PATH = './glove/'
BUILD_VOCAB = GLOVE_PATH + 'build_vocab.sh'
CUT_VOCAB = GLOVE_PATH + 'cut_vocab.sh'
PICKLE_VOCAB = GLOVE_PATH + 'pickle_vocab.py'
GLOVE_SOL = GLOVE_PATH + 'glove_solution.py'
COOC = GLOVE_PATH + 'cooc.py'
